/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventosmanejadores;

import java.awt.Color;
import java.awt.Font;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sun.print.BackgroundServiceLookup;

/**
 *
 * @author andre
 */
public class EventosManejadore extends javax.swing.JFrame {

    /**
     * Creates new form EventosManejadore
     */
    public EventosManejadore() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Boton1YS = new javax.swing.JButton();
        Boton2yFB = new javax.swing.JButton();
        Boton3SSBG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        Boton1YS.setText("Tamaños+Color");
        Boton1YS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1YSMouseClicked(evt);
            }
        });
        Boton1YS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1YSActionPerformed(evt);
            }
        });

        Boton2yFB.setText("Colores+Fuente");
        Boton2yFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2yFBActionPerformed(evt);
            }
        });

        Boton3SSBG.setText("Epilepsia");
        Boton3SSBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Boton3SSBGMouseMoved(evt);
            }
        });
        Boton3SSBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton3SSBGMouseClicked(evt);
            }
        });
        Boton3SSBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3SSBGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton3SSBG)
                    .addComponent(Boton2yFB)
                    .addComponent(Boton1YS))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Boton1YS)
                .addGap(130, 130, 130)
                .addComponent(Boton2yFB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(Boton3SSBG)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1YSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1YSMouseClicked
     
        System.out.println("Has clickeado el boton de Sysout");
        Boton1YS.setBackground(Color.red);
        Boton1YS.setSize(150,150);
           Boton2yFB.setForeground(Color.WHITE);
     
        
    }//GEN-LAST:event_Boton1YSMouseClicked

    private void Boton1YSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1YSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1YSActionPerformed

    private void Boton2yFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2yFBActionPerformed
        Font font = new Font("Agency FB", Font.BOLD, 14);
        System.out.println("Esto cambia las letras de Azul y el Background a amarillo");
        Background.setBackground(Color.YELLOW);
        Boton2yFB.setForeground(Color.MAGENTA);
        Boton1YS.setForeground(Color.orange);
        Boton1YS.setFont(font);
        Boton2yFB.setFont(font);
        Boton3SSBG.setFont(font);
       
    }//GEN-LAST:event_Boton2yFBActionPerformed

 
    private void Boton3SSBGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3SSBGMouseClicked
        System.err.println("Cambiando color random");
      
   
    }//GEN-LAST:event_Boton3SSBGMouseClicked

    private void Boton3SSBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3SSBGActionPerformed
      
    }//GEN-LAST:event_Boton3SSBGActionPerformed

    private void Boton3SSBGMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3SSBGMouseMoved
          System.err.println("Cuidado con la epilepsia");  
        
        int colorSelector = (int) (Math.random()*5);
     
        switch(colorSelector){
            case 1: Background.setBackground(Color.red);
                    Boton3SSBG.setBackground(Color.blue);
                    Boton3SSBG.setSize(100,100);
                    break;
                    case 2: Background.setBackground(Color.blue);
                    Boton3SSBG.setBackground(Color.red);
                                        Boton3SSBG.setSize(70,70);
                    break;
                    case 3: Background.setBackground(Color.magenta);
                    Boton3SSBG.setBackground(Color.black);
                                        Boton3SSBG.setSize(80,80);
                    break;
                    case 4: Background.setBackground(Color.black);
                    Boton3SSBG.setBackground(Color.magenta);
                                        Boton3SSBG.setSize(90,90);
                    break;
                    case 5: Background.setBackground(Color.cyan);
                    Boton3SSBG.setBackground(Color.white);
                                        Boton3SSBG.setSize(110,110);
                    break;
                    default: Background.setBackground(Color.white);
                    Boton3SSBG.setBackground(Color.cyan);
                                        Boton3SSBG.setSize(60,60);
                    break;
                    
        }
    }//GEN-LAST:event_Boton3SSBGMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventosManejadore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventosManejadore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventosManejadore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventosManejadore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventosManejadore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Boton1YS;
    private javax.swing.JButton Boton2yFB;
    private javax.swing.JButton Boton3SSBG;
    // End of variables declaration//GEN-END:variables
}
